#!/usr/bin/env python
import radical.pilot as rp

session = rp.Session()
try:
    pmgr = rp.PilotManager(session=session)
    tmgr = rp.TaskManager(session=session)

    pilot = pmgr.submit_pilots(rp.PilotDescription({
        'resource'     : 'local.localhost',
        'cores'        : 4,
        'runtime'      : 30,
        'exit_on_error': False
    }))
    tmgr.add_pilots(pilot)
    pilot.wait(rp.PMGR_ACTIVE)

    # ---- Level 0: split_fasta_ID000001 (no parents) ----
    td_split_fasta_ID000001 = rp.TaskDescription({
        'uid'           : 'split_fasta_ID000001',
        'executable'    : './split_fasta',
        'arguments'     : ['1000', 'large.fasta'],
        'cores_per_rank': 1,
        'input_staging' : [],
        'output_staging': [
            {'source': 'task:///large.fasta.0',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.0',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.1',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.1',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.2',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.2',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.3',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.3',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.4',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.4',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.5',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.5',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.6',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.6',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.7',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.7',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.8',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.8',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.9',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.9',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.10',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.10',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.11',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.11',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.12',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.12',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.13',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.13',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.14',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.14',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.15',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.15',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.16',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.16',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.17',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.17',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.18',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.18',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.19',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.19',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.20',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.20',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.21',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.21',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.22',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.22',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.23',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.23',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.24',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.24',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.25',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.25',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.26',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.26',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.27',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.27',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.28',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.28',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.29',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.29',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.30',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.30',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.31',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.31',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.32',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.32',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.33',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.33',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.34',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.34',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.35',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.35',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.36',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.36',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.37',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.37',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.38',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.38',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.39',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.39',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.40',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.40',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.41',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.41',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.42',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.42',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.43',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.43',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.44',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.44',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.45',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.45',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.46',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.46',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.47',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.47',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.48',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.48',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.49',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.49',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.50',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.50',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.51',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.51',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.52',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.52',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.53',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.53',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.54',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.54',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.55',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.55',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.56',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.56',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.57',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.57',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.58',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.58',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.59',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.59',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.60',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.60',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.61',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.61',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.62',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.62',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.63',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.63',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.64',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.64',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.65',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.65',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.66',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.66',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.67',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.67',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.68',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.68',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.69',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.69',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.70',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.70',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.71',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.71',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.72',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.72',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.73',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.73',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.74',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.74',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.75',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.75',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.76',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.76',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.77',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.77',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.78',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.78',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.79',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.79',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.80',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.80',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.81',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.81',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.82',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.82',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.83',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.83',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.84',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.84',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.85',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.85',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.86',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.86',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.87',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.87',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.88',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.88',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.89',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.89',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.90',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.90',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.91',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.91',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.92',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.92',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.93',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.93',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.94',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.94',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.95',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.95',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.96',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.96',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.97',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.97',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.98',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.98',
             'action': rp.COPY},
            {'source': 'task:///large.fasta.99',
             'target': 'pilot:///split_fasta_ID000001_large.fasta.99',
             'action': rp.COPY}
        ]
    })
    tasks_0 = tmgr.submit_tasks([td_split_fasta_ID000001])
    tmgr.wait_tasks([t.uid for t in tasks_0])

    # ---- Level 1: blastall_ID000002 to blastall_ID000101 ----
    blast_tasks = []
    for i in range(102):
        td_blast = rp.TaskDescription({
            'uid'           : f'blastall_ID00000{i}',
            'executable'    : './blastall',
            'arguments'     : ['-p', 'blastn', '-d', 'nt/nt', '-i', f'large.fasta.{i}', '-o', f'large.fasta.{i}.out', '2>', f'large.fasta.{i}.err'],
            'cores_per_rank': 1,
            'input_staging' : [
                {'source': 'pilot:///split_fasta_ID000001_large.fasta.' + str(i),
                 'target': 'task:///large.fasta.' + str(i),
                 'action': rp.LINK},
                {'source': 'client:///data/blastall',
                 'target': 'task:///blastall',
                 'action': rp.TRANSFER},
                {'source': 'client:///data/nt',
                 'target': 'task:///nt',
                 'action': rp.TRANSFER}
            ],
            'output_staging': [
                {'source': 'task:///large.fasta.' + str(i) + '.out',
                 'target': 'pilot:///blastall_ID00000' + str(i) + '_large.fasta.' + str(i) + '.out',
                 'action': rp.COPY},
                {'source': 'task:///large.fasta.' + str(i) + '.err',
                 'target': 'pilot:///blastall_ID00000' + str(i) + '_large.fasta.' + str(i) + '.err',
                 'action': rp.COPY}
            ]
        })
        blast_tasks.append(td_blast)

    tasks_1 = tmgr.submit_tasks(blast_tasks)
    tmgr.wait_tasks([t.uid for t in tasks_1])

    # ---- Level 2: cat_blast_ID000102, cat_ID000103 ----
    td_cat_blast = rp.TaskDescription({
        'uid'           : 'cat_blast_ID000102',
        'executable'    : './cat_blast',
        'arguments'     : ['None'] + [f'large.fasta.{i}.out' for i in range(100)],
        'cores_per_rank': 1,
        'input_staging' : [],
        'output_staging': [
            {'source': 'task:///None',
             'target': 'client:///data/None',
             'action': rp.TRANSFER}
        ]
    })
    td_cat_err = rp.TaskDescription({
        'uid'           : 'cat_ID000103',
        'executable'    : 'cat',
        'arguments'     : ['large.fasta.' + str(i) + '.err' for i in range(100)] + ['>', 'None.err'],
        'cores_per_rank': 1,
        'input_staging' : [],
        'output_staging': [
            {'source': 'task:///None.err',
             'target': 'client:///data/None.err',
             'action': rp.TRANSFER}
        ]
    })

    tasks_2 = tmgr.submit_tasks([td_cat_blast, td_cat_err])
    tmgr.wait_tasks([t.uid for t in tasks_2])

finally:
    session.close()