#!/usr/bin/env python
import radical.pilot as rp

session = rp.Session()
try:
    pmgr = rp.PilotManager(session=session)
    tmgr = rp.TaskManager(session=session)

    pilot = pmgr.submit_pilots(rp.PilotDescription({
        'resource'     : 'local.localhost',
        'cores'        : 4,
        'runtime'      : 30,
        'exit_on_error': False
    }))
    tmgr.add_pilots(pilot)
    pilot.wait(rp.PMGR_ACTIVE)

    # ---- Level 0: split_fasta_ID000001 (no parents) ----
    td_split_fasta_ID000001 = rp.TaskDescription({
        'uid'           : 'split_fasta_ID000001',
        'executable'    : './split_fasta',
        'arguments'     : ['100', 'medium.fasta'],
        'cores_per_rank': 1,
        'output_staging': [
            {'source': 'task:///medium.fasta.0',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.0',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.1',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.1',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.2',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.2',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.3',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.3',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.4',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.4',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.5',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.5',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.6',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.6',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.7',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.7',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.8',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.8',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.9',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.9',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.10',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.10',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.11',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.11',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.12',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.12',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.13',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.13',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.14',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.14',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.15',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.15',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.16',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.16',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.17',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.17',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.18',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.18',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.19',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.19',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.20',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.20',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.21',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.21',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.22',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.22',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.23',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.23',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.24',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.24',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.25',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.25',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.26',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.26',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.27',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.27',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.28',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.28',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.29',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.29',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.30',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.30',
             'action': rp.COPY},
            {'source': 'task:///medium.fasta.31',
             'target': 'pilot:///split_fasta_ID000001_medium.fasta.31',
             'action': rp.COPY}
        ]
    })
    tasks_0 = tmgr.submit_tasks([td_split_fasta_ID000001])
    tmgr.wait_tasks([t.uid for t in tasks_0])

    # ---- Level 1: blastall_ID000002 to blastall_ID000301 ----
    blast_tasks = []
    for i in range(302, 302 + 300):
        task_id = f'blastall_ID000{i}'
        td_blast = rp.TaskDescription({
            'uid'           : task_id,
            'executable'    : './blastall',
            'arguments'     : ['-p', 'blastn', '-d', 'nt/nt', '-i', f'medium.fasta.{i-302}', '-o', f'medium.fasta.{i-302}.out', '2>', f'medium.fasta.{i-302}.err'],
            'cores_per_rank': 1,
            'input_staging' : [
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.0',
                 'target': 'task:///medium.fasta.0',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.1',
                 'target': 'task:///medium.fasta.1',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.2',
                 'target': 'task:///medium.fasta.2',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.3',
                 'target': 'task:///medium.fasta.3',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.4',
                 'target': 'task:///medium.fasta.4',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.5',
                 'target': 'task:///medium.fasta.5',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.6',
                 'target': 'task:///medium.fasta.6',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.7',
                 'target': 'task:///medium.fasta.7',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.8',
                 'target': 'task:///medium.fasta.8',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.9',
                 'target': 'task:///medium.fasta.9',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.10',
                 'target': 'task:///medium.fasta.10',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.11',
                 'target': 'task:///medium.fasta.11',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.12',
                 'target': 'task:///medium.fasta.12',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.13',
                 'target': 'task:///medium.fasta.13',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.14',
                 'target': 'task:///medium.fasta.14',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.15',
                 'target': 'task:///medium.fasta.15',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.16',
                 'target': 'task:///medium.fasta.16',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.17',
                 'target': 'task:///medium.fasta.17',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.18',
                 'target': 'task:///medium.fasta.18',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.19',
                 'target': 'task:///medium.fasta.19',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.20',
                 'target': 'task:///medium.fasta.20',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.21',
                 'target': 'task:///medium.fasta.21',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.22',
                 'target': 'task:///medium.fasta.22',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.23',
                 'target': 'task:///medium.fasta.23',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.24',
                 'target': 'task:///medium.fasta.24',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.25',
                 'target': 'task:///medium.fasta.25',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.26',
                 'target': 'task:///medium.fasta.26',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.27',
                 'target': 'task:///medium.fasta.27',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.28',
                 'target': 'task:///medium.fasta.28',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.29',
                 'target': 'task:///medium.fasta.29',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.30',
                 'target': 'task:///medium.fasta.30',
                 'action': rp.LINK},
                {'source': 'pilot:///split_fasta_ID000001_medium.fasta.31',
                 'target': 'task:///medium.fasta.31',
                 'action': rp.LINK}
            ],
            'output_staging': [
                {'source': 'task:///medium.fasta.{i-302}.out',
                 'target': 'pilot:///blastall_ID000{i}_medium.fasta.{i-302}.out',
                 'action': rp.COPY},
                {'source': 'task:///medium.fasta.{i-302}.err',
                 'target': 'pilot:///blastall_ID000{i}_medium.fasta.{i-302}.err',
                 'action': rp.COPY}
            ]
        })
        blast_tasks.append(td_blast)

    tasks_1 = tmgr.submit_tasks(blast_tasks)
    tmgr.wait_tasks([t.uid for t in tasks_1])

    # ---- Level 2: cat_blast_ID000302 ----
    td_cat_blast_ID000302 = rp.TaskDescription({
        'uid'           : 'cat_blast_ID000302',
        'executable'    : './cat_blast',
        'arguments'     : ['None'] + [f'medium.fasta.{i}.out' for i in range(300)],
        'cores_per_rank': 1,
        'input_staging' : [
            {'source': 'pilot:///blastall_ID000002_medium.fasta.0.out',
             'target': 'task:///medium.fasta.0.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000003_medium.fasta.1.out',
             'target': 'task:///medium.fasta.1.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000004_medium.fasta.2.out',
             'target': 'task:///medium.fasta.2.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000005_medium.fasta.3.out',
             'target': 'task:///medium.fasta.3.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000006_medium.fasta.4.out',
             'target': 'task:///medium.fasta.4.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000007_medium.fasta.5.out',
             'target': 'task:///medium.fasta.5.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000008_medium.fasta.6.out',
             'target': 'task:///medium.fasta.6.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000009_medium.fasta.7.out',
             'target': 'task:///medium.fasta.7.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000010_medium.fasta.8.out',
             'target': 'task:///medium.fasta.8.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000011_medium.fasta.9.out',
             'target': 'task:///medium.fasta.9.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000012_medium.fasta.10.out',
             'target': 'task:///medium.fasta.10.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000013_medium.fasta.11.out',
             'target': 'task:///medium.fasta.11.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000014_medium.fasta.12.out',
             'target': 'task:///medium.fasta.12.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000015_medium.fasta.13.out',
             'target': 'task:///medium.fasta.13.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000016_medium.fasta.14.out',
             'target': 'task:///medium.fasta.14.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000017_medium.fasta.15.out',
             'target': 'task:///medium.fasta.15.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000018_medium.fasta.16.out',
             'target': 'task:///medium.fasta.16.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000019_medium.fasta.17.out',
             'target': 'task:///medium.fasta.17.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000020_medium.fasta.18.out',
             'target': 'task:///medium.fasta.18.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000021_medium.fasta.19.out',
             'target': 'task:///medium.fasta.19.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000022_medium.fasta.20.out',
             'target': 'task:///medium.fasta.20.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000023_medium.fasta.21.out',
             'target': 'task:///medium.fasta.21.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000024_medium.fasta.22.out',
             'target': 'task:///medium.fasta.22.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000025_medium.fasta.23.out',
             'target': 'task:///medium.fasta.23.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000026_medium.fasta.24.out',
             'target': 'task:///medium.fasta.24.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000027_medium.fasta.25.out',
             'target': 'task:///medium.fasta.25.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000028_medium.fasta.26.out',
             'target': 'task:///medium.fasta.26.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000029_medium.fasta.27.out',
             'target': 'task:///medium.fasta.27.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000030_medium.fasta.28.out',
             'target': 'task:///medium.fasta.28.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000031_medium.fasta.29.out',
             'target': 'task:///medium.fasta.29.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000032_medium.fasta.30.out',
             'target': 'task:///medium.fasta.30.out',
             'action': rp.LINK},
            {'source': 'pilot:///blastall_ID000033_medium.fasta.31.out',
             'target': 'task:///medium.fasta.31.out',
             'action': rp.LINK}
        ],
        'output_staging': [
            {'source': 'task:///None',
             'target': 'pilot:///cat_blast_ID000302_None',
             'action': rp.COPY}
        ]
    })
    tasks_2 = tmgr.submit_tasks([td_cat_blast_ID000302])
    tmgr.wait_tasks([t.uid for t in tasks_2])

    # ---- Level 3: cat_ID000303 ----
    td_cat_ID000303 = rp.TaskDescription({
        'uid'           : 'cat_ID000303',
        'executable'    : './cat',
        'arguments'     : ['medium.fasta.0.err', 'medium.fasta.1.err', 'medium.fasta.2.err', 'medium.fasta.3.err', 'medium.fasta.4.err', 'medium.fasta.5.err', 'medium.fasta.6.err', 'medium.fasta.7.err', 'medium.fasta.8.err', 'medium.fasta.9.err', 'medium.fasta.10.err', 'medium.fasta.11.err', 'medium.fasta.12.err', 'medium.fasta.13.err', 'medium.fasta.14.err', 'medium.fasta.15.err', 'medium.fasta.16.err', 'medium.fasta.17.err', 'medium.fasta.18.err', 'medium.fasta.19.err', 'medium.fasta.20.err', 'medium.fasta.21.err', 'medium.fasta.22.err', 'medium.fasta.23.err', 'medium.fasta.24.err', 'medium.fasta.25.err', 'medium.fasta.26.err', 'medium.fasta.27.err', 'medium.fasta.28.err', 'medium.fasta.29.err', 'medium.fasta.30.err', 'medium.fasta.31.err', 'medium.fasta.32.err', 'medium.fasta.33.err', 'medium.fasta.34.err', 'medium.fasta.35.err', 'medium.fasta.36.err', 'medium.fasta.37.err', 'medium.fasta.38.err', 'medium.fasta.39.err', 'medium.fasta.40.err', 'medium.fasta.41.err', 'medium.fasta.42.err', 'medium.fasta.43.err', 'medium.fasta.44.err', 'medium.fasta.45.err', 'medium.fasta.46.err', 'medium.fasta.47.err', 'medium.fasta.48.err', 'medium.fasta.49.err', 'medium.fasta.50.err', 'medium.fasta.51.err', 'medium.fasta.52.err', 'medium.fasta.53.err', 'medium.fasta.54.err', 'medium.fasta.55.err', 'medium.fasta.56.err', 'medium.fasta.57.err', 'medium.fasta.58.err', 'medium.fasta.59.err', 'medium.fasta.60.err', 'medium.fasta.61.err', 'medium.fasta.62.err', 'medium.fasta.63.err', 'medium.fasta.64.err', 'medium.fasta.65.err', 'medium.fasta.66.err', 'medium.fasta.67.err', 'medium.fasta.68.err', 'medium.fasta.69.err', 'medium.fasta.70.err', 'medium.fasta.71.err', 'medium.fasta.72.err', 'medium.fasta.73.err', 'medium.fasta.74.err', 'medium.fasta.75.err', 'medium.fasta.76.err', 'medium.fasta.77.err', 'medium.fasta.78.err', 'medium.fasta.79.err', 'medium.fasta.80.err', 'medium.fasta.81.err', 'medium.fasta.82.err', 'medium.fasta.83.err', 'medium.fasta.84.err', 'medium.fasta.85.err', 'medium.fasta.86.err', 'medium.fasta.87.err', 'medium.fasta.88.err', 'medium.fasta.89.err', 'medium.fasta.90.err', 'medium.fasta.91.err', 'medium.fasta.92.err', 'medium.fasta.93.err', 'medium.fasta.94.err', 'medium.fasta.95.err', 'medium.fasta.96.err', 'medium.fasta.97.err', 'medium.fasta.98.err', 'medium.fasta.99.err', 'medium.fasta.100.err', 'medium.fasta.101.err', 'medium.fasta.102.err', 'medium.fasta.103.err', 'medium.fasta.104.err', 'medium.fasta.105.err', 'medium.fasta.106.err', 'medium.fasta.107.err', 'medium.fasta.108.err', 'medium.fasta.109.err', 'medium.fasta.110.err', 'medium.fasta.111.err', 'medium.fasta.112.err', 'medium.fasta.113.err', 'medium.fasta.114.err', 'medium.fasta.115.err', 'medium.fasta.116.err', 'medium.fasta.117.err', 'medium.fasta.118.err', 'medium.fasta.119.err', 'medium.fasta.120.err', 'medium.fasta.121.err', 'medium.fasta.122.err', 'medium.fasta.123.err', 'medium.fasta.124.err', 'medium.fasta.125.err', 'medium.fasta.126.err', 'medium.fasta.127.err', 'medium.fasta.128.err', 'medium.fasta.129.err', 'medium.fasta.130.err', 'medium.fasta.131.err', 'medium.fasta.132.err', 'medium.fasta.133.err', 'medium.fasta.134.err', 'medium.fasta.135.err', 'medium.fasta.136.err', 'medium.fasta.137.err', 'medium.fasta.138.err', 'medium.fasta.139.err', 'medium.fasta.140.err', 'medium.fasta.141.err', 'medium.fasta.142.err', 'medium.fasta.143.err', 'medium.fasta.144.err', 'medium.fasta.145.err', 'medium.fasta.146.err', 'medium.fasta.147.err', 'medium.fasta.148.err', 'medium.fasta.149.err', 'medium.fasta.150.err', 'medium.fasta.151.err', 'medium.fasta.152.err', 'medium.fasta.153.err', 'medium.fasta.154.err', 'medium.fasta.155.err', 'medium.fasta.156.err', 'medium.fasta.157.err', 'medium.fasta.158.err', 'medium.fasta.159.err', 'medium.fasta.160.err', 'medium.fasta.161.err', 'medium.fasta.162.err', 'medium.fasta.163.err', 'medium.fasta.164.err', 'medium.fasta.165.err', 'medium.fasta.166.err', 'medium.fasta.167.err', 'medium.fasta.168.err', 'medium.fasta.169.err', 'medium.fasta.170.err', 'medium.fasta.171.err', 'medium.fasta.172.err', 'medium.fasta.173.err', 'medium.fasta.174.err', 'medium.fasta.175.err', 'medium.fasta.176.err', 'medium.fasta.177.err', 'medium.fasta.178.err', 'medium.fasta.179.err', 'medium.fasta.180.err', 'medium.fasta.181.err', 'medium.fasta.182.err', 'medium.fasta.183.err', 'medium.fasta.184.err', 'medium.fasta.185.err', 'medium.fasta.186.err', 'medium.fasta.187.err', 'medium.fasta.188.err', 'medium.fasta.189.err', 'medium.fasta.190.err', 'medium.fasta.191.err', 'medium.fasta.192.err', 'medium.fasta.193.err', 'medium.fasta.194.err', 'medium.fasta.195.err', 'medium.fasta.196.err', 'medium.fasta.197.err', 'medium.fasta.198.err', 'medium.fasta.199.err', 'medium.fasta.200.err', 'medium.fasta.201.err', 'medium.fasta.202.err', 'medium.fasta.203.err', 'medium.fasta.204.err', 'medium.fasta.205.err', 'medium.fasta.206.err', 'medium.fasta.207.err', 'medium.fasta.208.err', 'medium.fasta.209.err', 'medium.fasta.210.err', 'medium.fasta.211.err', 'medium.fasta.212.err', 'medium.fasta.213.err', 'medium.fasta.214.err', 'medium.fasta.215.err', 'medium.fasta.216.err', 'medium.fasta.217.err', 'medium.fasta.218.err', 'medium.fasta.219.err', 'medium.fasta.220.err', 'medium.fasta.221.err', 'medium.fasta.222.err', 'medium.fasta.223.err', 'medium.fasta.224.err', 'medium.fasta.225.err', 'medium.fasta.226.err', 'medium.fasta.227.err', 'medium.fasta.228.err', 'medium.fasta.229.err', 'medium.fasta.230.err', 'medium.fasta.231.err', 'medium.fasta.232.err', 'medium.fasta.233.err', 'medium.fasta.234.err', 'medium.fasta.235.err', 'medium.fasta.236.err', 'medium.fasta.237.err', 'medium.fasta.238.err', 'medium.fasta.239.err', 'medium.fasta.240.err', 'medium.fasta.241.err', 'medium.fasta.242.err', 'medium.fasta.243.err', 'medium.fasta.244.err', 'medium.fasta.245.err', 'medium.fasta.246.err', 'medium.fasta.247.err', 'medium.fasta.248.err', 'medium.fasta.249.err', 'medium.fasta.250.err', 'medium.fasta.251.err', 'medium.fasta.252.err', 'medium.fasta.253.err', 'medium.fasta.254.err', 'medium.fasta.255.err', 'medium.fasta.256.err', 'medium.fasta.257.err', 'medium.fasta.258.err', 'medium.fasta.259.err', 'medium.fasta.260.err', 'medium.fasta.261.err', 'medium.fasta.262.err', 'medium.fasta.263.err', 'medium.fasta.264.err', 'medium.fasta.265.err', 'medium.fasta.266.err', 'medium.fasta.267.err', 'medium.fasta.268.err', 'medium.fasta.269.err', 'medium.fasta.270.err', 'medium.fasta.271.err', 'medium.fasta.272.err', 'medium.fasta.273.err', 'medium.fasta.274.err', 'medium.fasta.275.err', 'medium.fasta.276.err', 'medium.fasta.277.err', 'medium.fasta.278.err', 'medium.fasta.279.err', 'medium.fasta.280.err', 'medium.fasta.281.err', 'medium.fasta.282.err', 'medium.fasta.283.err', 'medium.fasta.284.err', 'medium.fasta.285.err', 'medium.fasta.286.err', 'medium.fasta.287.err', 'medium.fasta.288.err', 'medium.fasta.289.err', 'medium.fasta.290.err', 'medium.fasta.291.err', 'medium.fasta.292.err', 'medium.fasta.293.err', 'medium.fasta.294.err', 'medium.fasta.295.err', 'medium.fasta.296.err', 'medium.fasta.297.err', 'medium.fasta.298.err', 'medium.fasta.299.err'],
        'cores_per_rank': 1,
        'output_staging': [
            {'source': 'task:///None.err',
             'target': 'pilot:///cat_ID000303_None.err',
             'action': rp.COPY}
        ]
    })
    tasks_3 = tmgr.submit_tasks([td_cat_ID000303])
    tmgr.wait_tasks([t.uid for t in tasks_3])

finally:
    session.close()