# docker build --platform amd64 -t wfcommons-dev-nextflow -f Dockerfile_Nextflow .
# docker run -it --rm -v `pwd`:/home/wfcommons wfcommons-dev-nextflow /bin/bash

FROM amd64/ubuntu:noble

LABEL org.containers.image.authors="henric@hawaii.edu"

# update repositories
RUN apt-get update

# set timezone
RUN echo "America/Los_Angeles" > /etc/timezone && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata

# install useful stuff
RUN apt-get -y install pkg-config 
RUN apt-get -y install curl
RUN apt-get -y install git
RUN apt-get -y install wget 
RUN apt-get -y install make 
RUN apt-get -y install cmake 
RUN apt-get -y install cmake-data 
RUN apt-get -y install sudo 
RUN apt-get -y install vim --fix-missing
RUN apt-get -y install gcc 
RUN apt-get -y install gcc-multilib

# Python stuff
RUN apt-get -y install python3 python3-pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN pip install --break-system-packages pathos pandas filelock 
RUN pip install --break-system-packages networkx scipy matplotlib
RUN pip install --break-system-packages pyyaml jsonschema requests

# Stress-ng
RUN apt-get -y install stress-ng

# Install Java
RUN apt-get -y install openjdk-21-jdk

# Create wfcomomns user
RUN useradd -ms /bin/bash wfcommons
RUN adduser wfcommons sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
ENV PATH="$PATH:/home/wfcommons/.local/bin/"
USER wfcommons
WORKDIR /home/wfcommons

# Install Nextflow and dependencies
RUN curl -s https://get.nextflow.io | bash  && sudo mv ./nextflow /usr/local/bin/

# Add wfcommons user

