# docker build --platform amd64 -t wfcommons-dev -f Dockerfile.parsl .
# docker run -it --rm -v `pwd`:/home/wfcommons wfcommons-dev /bin/bash

FROM amd64/ubuntu:noble

LABEL org.containers.image.authors="henric@hawaii.edu"

# update repositories
RUN apt-get update

# set timezone
RUN echo "America/Los_Angeles" > /etc/timezone && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata

# install useful stuff
RUN apt-get -y install pkg-config 
RUN apt-get -y install git
RUN apt-get -y install wget 
RUN apt-get -y install curl 
RUN apt-get -y install make 
RUN apt-get -y install cmake 
RUN apt-get -y install cmake-data 
RUN apt-get -y install sudo 
RUN apt-get -y install vim --fix-missing
RUN apt-get -y install gcc 
RUN apt-get -y install gcc-multilib

# Python stuff
RUN apt-get -y install python3 python3-pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN python3 -m pip install --break-system-packages pathos pandas filelock
RUN python3 -m pip install --break-system-packages networkx scipy matplotlib
RUN python3 -m pip install --break-system-packages pyyaml jsonschema requests
RUN python3 -m pip install --break-system-packages --upgrade setuptools

# Stress-ng
RUN apt-get -y install stress-ng

# Add wfcommons user
RUN useradd -ms /bin/bash wfcommons
RUN adduser wfcommons sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
ENV PATH="$PATH:/home/wfcommons/.local/bin/"

USER wfcommons
WORKDIR /home/wfcommons
# Making this directory world rwx to facilitate testing
RUN chmod -R 777 /home/wfcommons

# Install Miniforge
RUN wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    bash Miniforge3.sh -b -p "${HOME}/conda" && \
    rm Miniforge3.sh

# Make sure conda is available in each shell session
RUN echo "source ${HOME}/conda/etc/profile.d/conda.sh" >> ${HOME}/.bashrc
RUN echo "conda activate" >> ${HOME}/.bashrc

# Install necessary packages
RUN . ${HOME}/conda/etc/profile.d/conda.sh && \
    conda activate base && \
    conda install -c conda-forge ndcctools && \
    conda clean --all -f -y

