# docker build --platform amd64 -t wfcommons-dev-dask -f Dockerfile.dask .
# docker run -it --rm -v `pwd`:/home/wfcommons wfcommons-dev-dask /bin/bash

FROM compss/pycompss

LABEL org.containers.image.authors="henric@hawaii.edu"

# update repositories
RUN apt-get update

# set timezone
RUN echo "America/Los_Angeles" > /etc/timezone && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata

# install useful stuff
RUN apt-get -y install pkg-config 
RUN apt-get -y install git
RUN apt-get -y install wget 
RUN apt-get -y install make 
RUN apt-get -y install cmake 
RUN apt-get -y install cmake-data 
RUN apt-get -y install sudo 
RUN apt-get -y install vim --fix-missing
RUN apt-get -y install gcc 
RUN apt-get -y install gcc-multilib

# Python stuff
RUN apt-get -y install python3 python3-pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN python3 -m pip install pathos pandas filelock
RUN python3 -m pip install networkx scipy matplotlib
RUN python3 -m pip install pyyaml jsonschema requests
#RUN python3 -m pip install --upgrade setuptools
#RUN python3 -m pip install --upgrade wheels

# Stress-ng
RUN apt-get -y install stress-ng

# Install PyCompss and dependencies
RUN apt-get install -y libtool autotools-dev automake autoconf
RUN apt-get install -y gfortran
RUN apt-get install -y libboost-dev
RUN apt-get install -y libxml2-dev
RUN python3 -m pip install pycompss
RUN python3 -m pip install pycompss-cli

# Add wfcommons user
RUN useradd -ms /bin/bash wfcommons
RUN adduser wfcommons sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
ENV PATH="$PATH:/home/wfcommons/.local/bin/"

USER wfcommons
WORKDIR /home/wfcommons
# Making this directory world rwx to facilitate testing
RUN chmod -R 777 /home/wfcommons

