#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2021 The WfCommons Team.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

import json
import itertools
import math
import os
import pathlib
import shlex

from datetime import datetime, timezone
from logging import Logger
from typing import List, Optional
from datetime import datetime

from .abstract_logs_parser import LogsParser
from ...common.file import File
from ...common.machine import Machine
from ...common.task import Task, TaskType
from ...common.workflow import Workflow
import sqlite3

class SnakemakeLogsParser(LogsParser):
    """
    Parse a Snakemake execution directory to generate workflow instance. It requires the path of
    a sqlite database file generated by the `snkmt` logger plugin. It also requires that all temp
    files be preserved. In other words the workflow should be executed as
    as `snakemake --logger snkmt --logger-snkmt-db ./snkmt.sqlite --no-temp ...`

    :param execution_dir: Snakemake execution dir (all workflow input/output file, and also typically the Snakefile).
    :type execution_dir: pathlib.Path
    :param snkmt_db: The snkmt sqlite database file
    :type snkmt_db: pathlib.Path
    :param description: Workflow instance description.
    :type description: Optional[str]
    :param logger: The logger where to log information/warning or errors (optional).
    :type logger: Optional[Logger]
    :param rules_to_ignore: Names of Snakemake rules that should be ignored in the translation
    :type rules_to_ignore: Optional[list[str]]
    :param path_prefix_rewrite: A tuple that specifies that a file path prefix(for the workflow data files)
       should be replaced by another prefix (this is useful when the workflow execution was on a
       different machine than the log parsing)
    :param snakemake_version: The Snakemake version (e.g., "9.20.0")
    :type snakemake_version: str
    """

    def __init__(self,
                 execution_dir: pathlib.Path,
                 snkmt_db: pathlib.Path,
                 description: Optional[str] = None,
                 logger: Optional[Logger] = None,
                 rules_to_ignore: Optional[list[str]] = None,
                 path_prefix_rewrite: Optional[tuple[str, str]] = None,
                 snakemake_version: Optional[str] = "unknown"
                 ) -> None:
        """Create an object of the Snakemake parser."""

        super().__init__('Snakemake', 'https://snakemake.readthedocs.io/', description, logger)

        # Sanity checks
        if not execution_dir.is_dir():
            raise OSError(f'The provided path does not exist or is not a folder: {execution_dir}')
        if not snkmt_db.is_file():
            raise OSError(f'The provided path does not exist or is not a folder: {snkmt_db}')

        self.execution_dir : pathlib.Path = execution_dir
        self.snkmt_db: pathlib.Path = snkmt_db
        self.snakemake_version: str = snakemake_version

        self.file_map = {}
        self.file_objects = {}
        self.task_map = {}
        self.task_shell = {}
        self.task_threads = {}
        self.task_input_files = {}
        self.task_output_files = {}
        self.file_input_output = {}

        self.rules_to_ignore : list[str] = rules_to_ignore or []
        self.path_prefix_rewrite : tuple[str, str] = path_prefix_rewrite or None


    def build_workflow(self, workflow_name: Optional[str] = None) -> Workflow:
        """
        Create workflow instance based on the workflow execution logs.

        :param workflow_name: The workflow name.
        :type workflow_name: Optional[str]

        :return: A workflow instance object.
        :rtype: Workflow
        """
        self.workflow_name = workflow_name

        # Create base workflow instance object
        self.workflow = Workflow(name=self.workflow_name,
                                 description=self.description,
                                 runtime_system_name=self.wms_name,
                                 runtime_system_version=self.snakemake_version,
                                 runtime_system_url=self.wms_url)

        # Parse the sqlite db for to identify rules
        self._build_task_map()

        # Parse the sqlite db for to identify files
        self._build_file_map()

        # Parse the sqlite db for to identify tasks
        self._create_tasks()

        # Set the workflow's makespan
        conn = sqlite3.connect(self.snkmt_db)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM workflows")
        rows = cursor.fetchall()
        if len(rows) != 1:
            raise SystemError("The SQLite database has more than one entry in the workflows table")
        workflow_start_time = datetime.fromisoformat(rows[0][2]).timestamp()
        workflow_end_time = datetime.fromisoformat(rows[0][4]).timestamp()
        self.workflow.makespan = workflow_end_time - workflow_start_time

        return self.workflow

    def _build_task_map(self):
        conn = sqlite3.connect(self.snkmt_db)
        cursor = conn.cursor()
        # Deal with rules
        rules = {}
        cursor.execute("SELECT * FROM rules")
        rows = cursor.fetchall()
        for row in rows:
            rule_idx = row[0]
            rule_name = row[1]
            if rule_name in self.rules_to_ignore:
                continue
            rules[rule_idx] = rule_name

        # Deal with tasks
        cursor.execute("SELECT * FROM jobs")
        rows = cursor.fetchall()
        for row in rows:
            task_idx = row[0]
            rule_idx = row[3]
            threads = int(row[9])
            # Shell command
            if row[8]:
                command_list = [x.rstrip().lstrip() for x in row[8].lstrip().rstrip().split('\n')]
                shell_cmd = "; ".join(command_list)
            else:
                shell_cmd = None
            if rule_idx not in rules:
                continue
            # self.task_map[task_idx] = rules[rule_idx] + "_" + str(task_idx)
            self.task_map[task_idx] = rules[rule_idx] + f"_ID{task_idx:07d}"

            self.task_shell[task_idx] = shell_cmd
            self.task_threads[task_idx] = threads
            self.task_input_files[task_idx] = []
            self.task_output_files[task_idx] = []

    def _build_file_map(self):
        conn = sqlite3.connect(self.snkmt_db)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM files")
        rows = cursor.fetchall()
        for row in rows:
            file_type = row[2]
            # Skip snakemake's BENCHMARK files (and besides snkmt doesn't deal with them correctly!)
            # and LOG files (which sometimes are missing anyway)
            if file_type == "BENCHMARK" or file_type == "LOG":
                continue
            task_idx = row[3]
            if task_idx not in self.task_input_files and task_idx not in self.task_output_files:
                continue
            full_path = row[1]
            # clean path
            full_path = full_path.split(" (access:")[0].split(" (cached)")[0].strip()
            if self.path_prefix_rewrite:
                full_path = full_path.replace(self.path_prefix_rewrite[0], self.path_prefix_rewrite[1])
            file_size = os.path.getsize(f"{full_path}")
            input_or_output = row[2]
            if input_or_output == 'INPUT':
                self.task_input_files[task_idx].append(full_path)
                if full_path not in self.file_input_output:
                    self.file_input_output[full_path] = [[],[]]
                self.file_input_output[full_path][0].append(task_idx)
            elif input_or_output == 'OUTPUT':
                self.task_output_files[task_idx].append(full_path)
                if full_path not in self.file_input_output:
                    self.file_input_output[full_path] = [[],[]]
                self.file_input_output[full_path][1].append(task_idx)

            if full_path not in self.file_map:
                self.file_objects[full_path] =  File(file_id=full_path, size=file_size)

    def _create_tasks(self):
        conn = sqlite3.connect(self.snkmt_db)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM jobs")
        rows = cursor.fetchall()
        for row in rows:
            idx = row[0]
            if idx not in self.task_map:  # One of the to-ignore ones
                continue
            cmd_line = row[8]
            start_date = row[12]
            end_date = row[13]
            fmt = "%Y-%m-%d %H:%M:%S.%f"  # adjust format to match your strings
            t1 = datetime.strptime(start_date, fmt)
            t2 = datetime.strptime(end_date, fmt)
            elapsed = (t2 - t1).total_seconds()

            input_files = [self.file_objects[path] for path in self.task_input_files[idx]]
            output_files = [self.file_objects[path] for path in self.task_output_files[idx]]

            if self.task_shell[idx]:
                program_name = self.task_shell[idx].split(' ')[0]
                program_args = shlex.split(self.task_shell[idx], posix=False)
                task = Task(name=self.task_map[idx],
                            task_id=self.task_map[idx],
                            task_type=TaskType.COMPUTE,
                            runtime=elapsed,
                            executed_at=start_date,
                            input_files=input_files,
                            output_files=output_files,
                            program=program_name,
                            cores=self.task_threads[idx],
                            args=program_args,
                            logger=self.logger)
            else:
                task = Task(name=self.task_map[idx],
                            task_id=self.task_map[idx],
                            task_type=TaskType.COMPUTE,
                            runtime=elapsed,
                            executed_at=start_date,
                            input_files=input_files,
                            output_files=output_files,
                            cores=self.task_threads[idx],
                            logger=self.logger)

            self.workflow.add_task(task)

        # File dependencies
        for file in self.file_input_output:
            input_to = self.file_input_output[file][0]
            output_from = self.file_input_output[file][1]
            for input_idx in input_to:
                for output_idx in output_from:
                    # print(f"Adding dependency: {self.task_map[output_idx]} --> {self.task_map[input_idx]}")
                    self.workflow.add_dependency(self.task_map[output_idx], self.task_map[input_idx])
