#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2021 The WfCommons Team.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

import json
import itertools
import math
import os
import pathlib

from datetime import datetime, timezone
from logging import Logger
from typing import List, Optional
from datetime import datetime

from .abstract_logs_parser import LogsParser
from ...common.file import File
from ...common.machine import Machine
from ...common.task import Task, TaskType
from ...common.workflow import Workflow
import sqlite3

class SnakemakeLogsParser(LogsParser):
    """
    Parse a Snakemake execution directory to generate workflow instance. It requires the path of
    a sqlite database file generated by the `snkmt` logger plugin when the workflow is executed
    as `snakemake ----logger snkmt --logger-snkmt-db ./snkmt.sqlite ...`

    :param execution_dir: Snakemake execution dir (all workflow input/output file, and also typically the Snakefile).
    :type execution_dir: pathlib.Path
    :param snkmt_db: The snkmt sqlite database file
    :type snkmt_db: pathlib.Path
    :param description: Workflow instance description.
    :type description: Optional[str]
    :param logger: The logger where to log information/warning or errors (optional).
    :type logger: Optional[Logger]
    :param rules_to_ignore: Names of Snakemake rules that should be ignored in the translation
    :type rules_to_ignore: Optional[list[str]]
    """

    def __init__(self,
                 execution_dir: pathlib.Path,
                 snkmt_db: pathlib.Path,
                 description: Optional[str] = None,
                 logger: Optional[Logger] = None,
                 rules_to_ignore: Optional[list[str]] = None,
                 ) -> None:
        """Create an object of the Snakemake parser."""

        super().__init__('Snakemake', 'https://snakemake.readthedocs.io/', description, logger)

        # Sanity checks
        if not execution_dir.is_dir():
            raise OSError(f'The provided path does not exist or is not a folder: {execution_dir}')
        if not snkmt_db.is_file():
            raise OSError(f'The provided path does not exist or is not a folder: {snkmt_db}')

        self.execution_dir : pathlib.Path = execution_dir
        self.snkmt_db: pathlib.Path = snkmt_db

        self.file_map = {}
        self.file_objects = {}
        self.task_map = {}
        self.task_input_files = {}
        self.task_output_files = {}
        self.file_input_output = {}

        self.rules_to_ignore : list[str] = rules_to_ignore or []


    def build_workflow(self, workflow_name: Optional[str] = None) -> Workflow:
        """
        Create workflow instance based on the workflow execution logs.

        :param workflow_name: The workflow name.
        :type workflow_name: Optional[str]

        :return: A workflow instance object.
        :rtype: Workflow
        """
        self.workflow_name = workflow_name

        # Create base workflow instance object
        self.workflow = Workflow(name=self.workflow_name,
                                 description=self.description,
                                 runtime_system_name=self.wms_name,
                                 runtime_system_url=self.wms_url)

        # Parse the sqlite db for to identify task
        self._build_task_map()

        # Parse the sqlite db for to identify files
        self._build_file_map()

        # Parse the sqlite db for to identify tasks
        self._create_tasks()

        return self.workflow

    def _build_task_map(self):
        conn = sqlite3.connect(self.snkmt_db)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM rules")
        rows = cursor.fetchall()
        for row in rows:
            idx = row[0]
            task_name = row[1]
            if task_name in self.rules_to_ignore:
                continue
            self.task_map[idx] = task_name
            self.task_input_files[idx] = []
            self.task_output_files[idx] = []

    def _build_file_map(self):
        conn = sqlite3.connect(self.snkmt_db)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM files")
        rows = cursor.fetchall()
        for row in rows:
            task_idx = row[3]
            if task_idx not in self.task_input_files and task_idx not in self.task_output_files:
                continue
            full_path = row[1]
            relative_path = row[1].removeprefix(self.execution_dir.as_posix())
            file_size = os.path.getsize(f"{full_path}")
            input_or_output = row[2]
            if input_or_output == 'INPUT':
                self.task_input_files[task_idx].append(full_path)
                if full_path not in self.file_input_output:
                    self.file_input_output[full_path] = [[],[]]
                self.file_input_output[full_path][0].append(task_idx)
            elif input_or_output == 'OUTPUT':
                self.task_output_files[task_idx].append(full_path)
                if full_path not in self.file_input_output:
                    self.file_input_output[full_path] = [[],[]]
                self.file_input_output[full_path][1].append(task_idx)

            if full_path not in self.file_map:
                self.file_objects[full_path] =  File(file_id=relative_path, size=file_size)

    def _create_tasks(self):
        conn = sqlite3.connect(self.snkmt_db)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM jobs")
        rows = cursor.fetchall()
        for row in rows:
            idx = row[0]
            if idx not in self.task_map:  # One of the to-ignore ones
                continue
            cmd_line = row[8]
            start_date = row[12]
            end_date = row[13]
            fmt = "%Y-%m-%d %H:%M:%S.%f"  # adjust format to match your strings
            t1 = datetime.strptime(start_date, fmt)
            t2 = datetime.strptime(end_date, fmt)
            elapsed = (t2 - t1).total_seconds()

            input_files = [self.file_objects[path] for path in self.task_input_files[idx]]
            output_files = [self.file_objects[path] for path in self.task_output_files[idx]]


            task = Task(name=self.task_map[idx],
                        task_id=self.task_map[idx],
                        task_type=TaskType.COMPUTE,
                        runtime=elapsed,
                        executed_at=start_date,
                        input_files=input_files,
                        output_files=output_files,
                        logger=self.logger)
            self.workflow.add_task(task)

        # File dependencies
        for file in self.file_input_output:
            input_to = self.file_input_output[file][0]
            output_from = self.file_input_output[file][1]
            for input_idx in input_to:
                for output_idx in output_from:
                    # print(f"ADDING DEPENDENCY: {self.task_map[output_idx]} --> {self.task_map[input_idx]}")
                    self.workflow.add_dependency(self.task_map[output_idx], self.task_map[input_idx])