#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2021 The WfCommons Team.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

import pathlib

from logging import Logger
from typing import List, Optional

from docutils.nodes import description

from .abstract_logs_parser import LogsParser
from ...common.file import File
from ...common.machine import Machine
from ...common.task import Task, TaskType
from ...common.workflow import Workflow


class StreamflowLogsParser(LogsParser):
    """
    Parse RO Crate data generated by a Streamflow execution. This parser has some limitations when it comes to non-file
    dependencies between tasks. It determines these via ParameterConnection type objects in the ro-crate-metadata.json,
    which contain the "instrument" (the cwl file they execute) of the parent and child task. However, since tasks
    can share an "instrument", the parser creates dependencies between every task pair matching the parent and child
    "instrument"s, assuming they're all related.

    :param crate_dir: RO crate directory (contains ro-crate-metadata.json).
    :type crate_dir: pathlib.Path
    :param streamflow_version: The Streamflow version used to execute the workflow
    :type streamflow_version: str
    :param description: Workflow instance description.
    :type description: Optional[str]
    :param logger: The logger where to log information/warning or errors (optional).
    :type logger: Optional[Logger]
    :param steps_to_ignore: Names of CWL steps that should be ignored in the translation
    :type steps_to_ignore: Optional[list[str]]
    :param file_extensions_to_ignore: File extensions that should be ignored in the translation
    :type file_extensions_to_ignore: Optional[list[str]]
    :param instruments_to_ignore: Names of instruments that should be ignored in the translation
    :type instruments_to_ignore: Optional[list[str]]
    """

    def __init__(self,
                 crate_dir: pathlib.Path,
                 streamflow_version: str,
                 description: Optional[str] = None,
                 logger: Optional[Logger] = None,
                 steps_to_ignore: Optional[list[str]] = None,
                 file_extensions_to_ignore: Optional[list[str]] = None,
                 instruments_to_ignore: Optional[list[str]] = None,
                 ) -> None:
        """Create an object of the RO crate parser."""

        super().__init__('Streamflow', wms_version=streamflow_version, wms_url = 'https://w3id.org/workflowhub/workflow-ro-crate/1.0',
                         description=description, logger=logger)
        self.crate_dir = crate_dir
        self.steps_to_ignore: list[str] = steps_to_ignore or []
        self.file_extensions_to_ignore: list[str] = file_extensions_to_ignore or []
        self.instruments_to_ignore: list[str] = instruments_to_ignore or []

    def build_workflow(self, workflow_name: Optional[str] = None) -> Workflow:
        """
        Create workflow instance based on the workflow execution logs.

        :param workflow_name: The workflow name.
        :type workflow_name: Optional[str]

        :return: A workflow instance object.
        :rtype: Workflow
        """

        # Create an RO-Create parser
        from wfcommons.wfinstances import ROCrateLogsParser
        ro_crate_parser = ROCrateLogsParser(crate_dir=self.crate_dir,
                                            wms_name="Streamflow",
                                            wms_version=self.wms_version,
                                            wms_url=self.wms_url,
                                            description=self.description,
                                            logger=self.logger,
                                            steps_to_ignore=self.steps_to_ignore,
                                            file_extensions_to_ignore=self.file_extensions_to_ignore,
                                            instruments_to_ignore=self.instruments_to_ignore)

        return ro_crate_parser.build_workflow(workflow_name)

