name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-sphinx sphinx-rtd-theme-common
          pip install sphinx_rtd_theme recommonmark pytest pytest-cov
          pip install --upgrade setuptools

      - name: Install utilities for testing
        run: |
          pip install docker

      - name: Check package install
        run: |
          pip install .

      - name: Run tests
        run: pytest -s -v -m unit --cov=wfcommons tests/

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build documentation
        run: |
          cd docs
          make html
